### ISSUE TITLE
Improve the page with the error message returned from ssclj when SS (2.20) service is down

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#604] opened 2016-01-20 11:24 UTC
@st Please check and close, if this was either fixed in >2.20 or a duplicate.

When the service is down, user sees the raw stacktrace on UI https://185.19.30.27

```
java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
    at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
    at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:189)
    at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.doExecute(CloseableHttpAsyncClientBase.java:67)
    at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.access$000(CloseableHttpAsyncClientBase.java:38)
    at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:57)
    at java.lang.Thread.run(Thread.java:745)
```

It's the raw stacktrace as it goes to /var/log/slipstream/ssclj/ssclj.log

```
2016-01-20 11:09:08,108 INFO  - :get /run/a5740197-347b-4d54-af1d-fb098a450a09 [no-authn-info] ?no-query-string no-body
2016-01-20 11:09:08,110 ERROR - error in HTTP handler
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:189)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.doExecute(CloseableHttpAsyncClientBase.java:67)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.access$000(CloseableHttpAsyncClientBase.java:38)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:57)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by konstan** [comment] 2016-01-20 11:25
Adding the screenshot.

![screen shot 2016-01-20 at 12 24 47](https://cloud.githubusercontent.com/assets/353767/12447512/d74c64d8-bf70-11e5-9afe-26f06e71d0d3.png)

**Comment by st** [comment] 2016-01-20 12:58
Duplicate of #589

**Closed by st** 2016-01-20 12:58 UTC
Labels: P00 Internal, S04 Proposed for Sprint, T3 Enhancement, ★★★
