### ISSUE TITLE
Call connector validation function during sync process

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamServer#37] opened 2013-09-10 20:22 UTC
E.g. the CliConnectorBase class validates the cloud credentials, but not during the synchronous part of the process.  This should be called earlier, such that no failed run is created and the user is notified during creation.

**Comment by schaubl** [comment] 2015-03-12 16:15
This still apply.
Promoting to Backlog.

**Comment by schaubl** [comment] 2015-03-14 14:05
Similar/duplicate of #66.

**Closed** 2018-07-24 14:18 UTC
Labels: S00 Backlog
