### ISSUE TITLE
deployment should run create scripts if the image has not been built

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#267] opened 2015-03-12 15:30 UTC
A deployment involving an image with a create script but that hasn't been built fails with a 209-Conflict error.  This is unfortunate for a couple of reasons:
  1.  On clouds that do not support creating images, these images cannot be used or reused by others.  This also imposes the same limitation on any deployment that uses those images.
  2. This makes it impossible to use the same image description for deployments that create images and those that do not.  (E.g., it will always be necessary to maintain separate images for the NuvlaBox and other clouds.)

The behavior should be modified so that the deployment will do the following:
  1. If the image has been built, then only the deployment script will be run when deploying the image.
  2. If the image has not been built, then the creation script will be run and then afterwards the deployment script will be run.

**Comment by schaubl** [comment] 2015-03-12 16:17
This is a duplicate of #33.

**Closed** 2015-03-30 15:07 UTC
Labels: S40 Ready to validate
