### ISSUE TITLE
As Alice++ I can provision a set of VMs, tolerating failures in the provisioning process, such that I can provision a large number of VMs in fewer operations

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamServer#221] opened 2014-12-02 18:22 UTC
This user story comes from CERN flagship on Helix Nebula

**Comment by konstan** [comment] 2015-03-02 14:21
Extend to tolerate on the level of VMs instantiation.

**Comment by konstan** [comment] 2015-03-02 14:37
Implementation is in https://github.com/slipstream/SlipStreamClient/issues/70

**Comment by loomis** [comment] 2015-03-02 15:43
Duplicate of slipstream/SlipStreamClient#70

**Closed by loomis** 2015-03-02 15:43 UTC
Labels: enhancement, S05 Ready to work
