### ISSUE TITLE
allow user to selectively terminate VMs that were not started via SS

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#157] opened 2014-04-22 10:00 UTC
In /dashboard allow users to select and terminate VMs that are not associated to any run.  VMs associated to runs (i.e. having SlipStream ID) shouldn't be allowed to be terminated this way.

**Comment by schaubl** [comment] 2015-03-14 16:14
Duplicate of #85.

**Closed** 2015-03-14 16:14 UTC
Labels: duplicate
