### ISSUE TITLE
Curves on the metering graph change colour each 15 seconds

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamServer#512] opened 2015-10-23 08:14 UTC
Even though no data sets were added/removed the colour of atos/exoscale/interoute was changing (see the screenshots).  And although the colour of the legends changes accordingly as well, the whole situation is rather confusing, especially when following differences between closely placed curves.

![screen shot 2015-10-23 at 10 06 16](https://cloud.githubusercontent.com/assets/353767/10687456/858a93ac-796d-11e5-8ee8-2d36009218be.png)

![screen shot 2015-10-23 at 10 07 16](https://cloud.githubusercontent.com/assets/353767/10687458/8da6792a-796d-11e5-83fa-324b992ea92b.png)

**Comment by rbf** [comment] 2015-10-26 10:20
Indeed it's an issue but related to UI.
Duplicate of slipstream/SlipStreamUI#454.
Closing this one.

**Closed by rbf** 2015-10-26 10:20 UTC
Labels: S04 Proposed for Sprint, T5 Bug, ★★
